# Generated by Django 5.1.4 on 2024-12-30 17:53

from django.db import migrations

from product.models.category import Category


def add_categories(apps, schema_editor):
    # Get the Category model dynamically
    category = apps.get_model('product', 'Category')

    # Insert rows into the Category table
    categories = [
        "املاک",
        "وسایل نقلیه",
        "کالای دیجیتال",
        "خانه و آشپزخانه",
        "وسایل شخصی",
        "سرگرمی",
        "سایر"
    ]

    for title in categories:
        category.objects.create(title=title)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_banner_item_id'),
    ]

    operations = [
        migrations.RunPython(add_categories)
    ]
