# Generated by Django 5.1.4 on 2024-12-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_add_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.CharField(help_text='The MIME type of the image file (e.g., image/jpeg).', max_length=50, verbose_name='Content Type')),
                ('image_data', models.BinaryField(help_text='The binary data of the image file.', verbose_name='Image Data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
