# Generated by Django 5.1.4 on 2024-12-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_image_table_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_file',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.OneToOneField(default=None, help_text='The image associated with this banner.', on_delete=django.db.models.deletion.CASCADE, to='product.image', verbose_name='Banner Image'),
        ),
    ]
