# Generated by Django 5.1.4 on 2025-01-01 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_replace_imagefield_with_image_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reserver_user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='transaction_status',
        ),
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='items', related_query_name='category', to='product.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', related_query_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
