# Generated by Django 5.1.4 on 2025-01-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_transaction_table_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
