# Generated by Django 5.1.4 on 2025-01-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_item_id_banner_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='category', to='product.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', related_query_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
