# Generated by Django 5.1.4 on 2025-01-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_add_state_and_is_banned_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('comment', models.TextField(blank=True, verbose_name='Buyer Comment')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'accepted')], default='pending', max_length=20, verbose_name='Request State')),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', related_query_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', related_query_name='purchase_requests', to='product.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-id'],
            }
        )
    ]
