# Generated by Django 5.1.4 on 2025-01-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_add_buyer_user_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_items', related_query_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer user'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20, verbose_name='Request State'),
        ),
    ]
