# Generated by Django 5.1.4 on 2025-01-24 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_item_is_banned_delete_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('spam', models.PositiveIntegerField(default=0)),
                ('amoral', models.PositiveIntegerField(default=0)),
                ('fraud', models.PositiveIntegerField(default=0)),
                ('illegal', models.PositiveIntegerField(default=0)),
                ('contact_issue', models.PositiveIntegerField(default=0)),
                ('other', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('REVIEWING', 'در صف بررسی'), ('ACCEPTED', 'قبول شده'), ('REJECTED', 'رد شده')], default='REVIEWING', max_length=128, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, choices=[('SPAM', 'تکراری یا اسپم'), ('AMORAL', 'غیر\u200cاخلاقی'), ('FRAUD', 'کلاهبرداری'), ('ILLEGAL', 'غیرقانونی'), ('PRICE_ISSUE', 'قیمت نادرست'), ('CONTACT_ISSUE', 'اطلاعات تماس نادرست'), ('CATEGORY_ISSUE', 'دسته\u200cبندی نادرست'), ('RESPONSIVENESS_ISSUE', 'ناموجودی یا پاسخگو نبودن'), ('OTHER', 'سایر دلایل')], default='OTHER', help_text='Notes from admin about this report.', null=True, verbose_name='Admin Note')),
                ('price_issue', models.PositiveIntegerField(default=0)),
                ('category_issue', models.PositiveIntegerField(default=0)),
                ('responsiveness_issue', models.PositiveIntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_report', to='product.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item Aggregated Report',
                'verbose_name_plural': 'Item Aggregated Reports',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('spam', models.PositiveIntegerField(default=0)),
                ('amoral', models.PositiveIntegerField(default=0)),
                ('fraud', models.PositiveIntegerField(default=0)),
                ('illegal', models.PositiveIntegerField(default=0)),
                ('contact_issue', models.PositiveIntegerField(default=0)),
                ('other', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('REVIEWING', 'در صف بررسی'), ('ACCEPTED', 'قبول شده'), ('REJECTED', 'رد شده')], default='REVIEWING', max_length=128, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, choices=[('SPAM', 'تکراری یا اسپم'), ('AMORAL', 'غیر\u200cاخلاقی'), ('FRAUD', 'کلاهبرداری'), ('ILLEGAL', 'غیرقانونی'), ('PRICE_ISSUE', 'قیمت نادرست'), ('CONTACT_ISSUE', 'اطلاعات تماس نادرست'), ('CATEGORY_ISSUE', 'دسته\u200cبندی نادرست'), ('RESPONSIVENESS_ISSUE', 'ناموجودی یا پاسخگو نبودن'), ('OTHER', 'سایر دلایل')], default='OTHER', help_text='Notes from admin about this report.', null=True, verbose_name='Admin Note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_report', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Aggregated Report',
                'verbose_name_plural': 'User Aggregated Reports',
            },
        ),
    ]
