# Generated by Django 5.1.4 on 2025-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreport',
            name='admin_note',
            field=models.CharField(blank=True, choices=[('SPAM', 'تکراری یا اسپم'), ('AMORAL', 'غیر\u200cاخلاقی'), ('FRAUD', 'کلاهبرداری'), ('ILLEGAL', 'غیرقانونی'), ('PRICE_ISSUE', 'قیمت نادرست'), ('CONTACT_ISSUE', 'اطلاعات تماس نادرست'), ('CATEGORY_ISSUE', 'دسته\u200cبندی نادرست'), ('RESPONSIVENESS_ISSUE', 'ناموجودی یا پاسخگو نبودن'), ('OTHER', 'سایر دلایل')], default='OTHER', help_text='Notes from admin about this report.', max_length=128, null=True, verbose_name='Admin Note'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='admin_note',
            field=models.CharField(blank=True, choices=[('SPAM', 'تکراری یا اسپم'), ('AMORAL', 'غیر\u200cاخلاقی'), ('FRAUD', 'کلاهبرداری'), ('ILLEGAL', 'غیرقانونی'), ('PRICE_ISSUE', 'قیمت نادرست'), ('CONTACT_ISSUE', 'اطلاعات تماس نادرست'), ('CATEGORY_ISSUE', 'دسته\u200cبندی نادرست'), ('RESPONSIVENESS_ISSUE', 'ناموجودی یا پاسخگو نبودن'), ('OTHER', 'سایر دلایل')], default='OTHER', help_text='Notes from admin about this report.', max_length=128, null=True, verbose_name='Admin Note'),
        ),
    ]
