# Generated by Django 5.1.4 on 2024-12-22 09:54

import user.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[user.services.validators.UserValidator.national_id_validator], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[user.services.validators.UserValidator.phone_validator], verbose_name='Phone Number'),
        ),
    ]
