# Generated by Django 5.1.4 on 2025-01-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OffenderUser',
        ),
    ]
