# Generated by Django 5.1.4 on 2025-01-29 05:12

import user.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_banned_delete_offenderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[user.services.validators.UserValidator.email_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[user.services.validators.UserValidator.national_id_validator], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, validators=[user.services.validators.UserValidator.phone_validator], verbose_name='Phone Number'),
        ),
    ]
